services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=bluegreen
    ports:
      - "43306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
