spring:
  config:
    activate:
      on-profile: blue

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql_blue:3306/bluegreen}
    username: ${SPRING_DATASOURCE_USERNAME:app_user}
    password: ${SPRING_DATASOURCE_PASSWORD:app_pass}
    driver-class-name: com.mysql.cj.jdbc.Driver

app:
  environment: blue
  build-number: ${BUILD_NUMBER:1}

logging:
  level:
    com.study.bluegreen: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [BLUE] %logger{36} - %msg%n"
