server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/bluegreen}
    username: ${SPRING_DATASOURCE_USERNAME:app_user}
    password: ${SPRING_DATASOURCE_PASSWORD:app_pass}
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
